# Generated by Django for the messaging feature
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0118_remove_workspaceuserproperties_product_tour_and_more'),
    ]

    operations = [
        # Create MessageRoom table
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='General discussion room')),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_rooms', to='db.project')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_rooms', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Message Room',
                'verbose_name_plural': 'Message Rooms',
                'db_table': 'message_rooms',
                'ordering': ('-created_at',),
            },
        ),
        
        # Create indexes for MessageRoom
        migrations.AddIndex(
            model_name='messageroom',
            index=models.Index(fields=['workspace'], name='message_room_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='messageroom',
            index=models.Index(fields=['project'], name='message_room_project_idx'),
        ),
        migrations.AddIndex(
            model_name='messageroom',
            index=models.Index(fields=['is_private'], name='message_room_private_idx'),
        ),
        migrations.AddIndex(
            model_name='messageroom',
            index=models.Index(fields=['is_archived'], name='message_room_archived_idx'),
        ),

        # Create Message table
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('is_reply', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='db.messageroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='db.user')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='db.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ('-created_at',),
            },
        ),
        
        # Create indexes for Message
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room'], name='message_room_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='message_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['reply_to'], name='message_reply_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted'], name='message_deleted_idx'),
        ),

        # Create MessageMember table
        migrations.CreateModel(
            name='MessageMember',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('view_props', models.JSONField(default=dict)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_rooms', to='db.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='db.messageroom')),
            ],
            options={
                'verbose_name': 'Message Member',
                'verbose_name_plural': 'Message Members',
                'db_table': 'message_members',
                'ordering': ('-created_at',),
            },
        ),
        
        # Create indexes and constraints for MessageMember
        migrations.AddIndex(
            model_name='messagemember',
            index=models.Index(fields=['room'], name='message_member_room_idx'),
        ),
        migrations.AddIndex(
            model_name='messagemember',
            index=models.Index(fields=['member'], name='message_member_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagemember',
            constraint=models.UniqueConstraint(fields=('room', 'member'), name='unique_room_member'),
        ),

        # Create MessageReaction table
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='db.user')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='db.message')),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'db_table': 'message_reactions',
                'ordering': ('-created_at',),
            },
        ),
        
        # Create indexes and constraints for MessageReaction
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='message_reaction_message_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['actor'], name='message_reaction_actor_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('message', 'actor', 'reaction'), name='unique_message_reaction'),
        ),

        # Create MessageNotification table
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notify_user', models.BooleanField(default=True)),
                ('snoozed_till', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_message_notifications', to='db.user')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message_notifications', to='db.user')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='db.message')),
                ('message_thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_notifications', to='db.message')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.workspace')),
            ],
            options={
                'verbose_name': 'Message Notification',
                'verbose_name_plural': 'Message Notifications',
                'db_table': 'message_notifications',
                'ordering': ('-created_at',),
            },
        ),
        
        # Create indexes for MessageNotification
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['member'], name='message_notification_member_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['message'], name='message_notification_message_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['workspace'], name='message_notification_workspace_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['project'], name='message_notification_project_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['read_at'], name='message_notification_read_idx'),
        ),
        migrations.AddIndex(
            model_name='messagenotification',
            index=models.Index(fields=['notify_user'], name='message_notification_notify_idx'),
        ),
    ]